/* FIXME: we should either make this file being autogenerated or make
 * surfaceflinger stop depending on these macros being defined */

/* Version number of package */
#define VERSION "0.10.0.1"

/* Name of package */
#define PACKAGE "gst-plugin-android"
